# Generated by Django 5.0.6 on 2026-07-08 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DomainEventRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("aggregate_id", models.UUIDField(db_index=True)),
                ("event_name", models.CharField(db_index=True, max_length=100)),
                ("occurred_at", models.DateTimeField()),
                ("payload", models.JSONField(default=dict)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tasks_domain_event",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["aggregate_id", "id"],
                        name="tasks_domai_aggrega_c90096_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Trivial"),
                            (2, "Low"),
                            (3, "Normal"),
                            (4, "High"),
                            (5, "Critical"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("blocked", "Blocked"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tasks_task",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="tasks_task_status_4a0a95_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="tasks_task_priorit_a900d4_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="tasks_task_created_5da2cb_idx"
                    ),
                ],
            },
        ),
    ]
