# Generated by Django 5.2.16 on 2026-07-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaineventrecord",
            name="entry_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="domaineventrecord",
            name="prev_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
