# Generated by Django 5.2.16 on 2026-07-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_domaineventrecord_entry_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaineventrecord",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="TaskSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("aggregate_id", models.UUIDField(db_index=True)),
                ("last_event_id", models.BigIntegerField()),
                ("state", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tasks_task_snapshot",
                "ordering": ["-last_event_id"],
                "indexes": [
                    models.Index(
                        fields=["aggregate_id", "-last_event_id"],
                        name="tasks_task__aggrega_84dfe8_idx",
                    )
                ],
            },
        ),
    ]
