# Generated by Django 5.2.16 on 2026-07-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_domaineventrecord_version_tasksnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskStatistics",
            fields=[
                (
                    "status",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "tasks_stats_by_status",
            },
        ),
    ]
