# Generated by Django 5.2.16 on 2026-07-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_taskstatistics"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditChainHead",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("count", models.BigIntegerField(default=0)),
                ("head_hash", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "db_table": "tasks_audit_chain_head",
            },
        ),
    ]
